<?php
require __DIR__ . "/vendor/autoload.php";

use Dotenv\Dotenv;

$dotenv = Dotenv::createImmutable(__DIR__);
$dotenv->load();

include("includes/auth.php");
include("config/db.php");
include("includes/lang.php");
include("includes/ai-cache.php");
include("includes/header.php");
include("includes/navbar.php");

$user_id = $_SESSION["user_id"] ?? null;

if (!$user_id) {
    die("User not logged in");
}

$ai_response = "";
$plan = [];
$tasks = [];
$usedCache = false;
$forceRefresh = isset($_GET["refresh_ai"]);

/* =========================
   LOCAL TRANSLATIONS
========================= */
function rpText($key) {
    global $lang;

    $texts = [
        "en" => [
            "cache_loaded" => "Loaded from cache. No new AI cost.",
            "generated_saved" => "Generated by AI and saved to cache.",
            "no_tasks" => "No pending tasks found. Add tasks first.",
            "priority" => "Priority",
            "type" => "Type",
            "deadline" => "Deadline",
            "time" => "Time",
            "why" => "Why",
            "refresh" => "Regenerate plan",
            "manual_task" => "Manual task",
            "ai_task" => "AI-generated material task",
            "critical" => "Critical",
            "high" => "High",
            "medium" => "Medium",
            "low" => "Low"
        ],

        "ru" => [
            "cache_loaded" => "Загружено из cache. Новый AI-запрос не использован.",
            "generated_saved" => "План создан AI и сохранён в cache.",
            "no_tasks" => "Нет заданий в процессе. Сначала добавьте задания.",
            "priority" => "Приоритет",
            "type" => "Тип",
            "deadline" => "Дедлайн",
            "time" => "Время",
            "why" => "Почему",
            "refresh" => "Создать заново",
            "manual_task" => "Ручное задание",
            "ai_task" => "AI-задание из материала",
            "critical" => "Критический",
            "high" => "Высокий",
            "medium" => "Средний",
            "low" => "Низкий"
        ],

        "kz" => [
            "cache_loaded" => "Cache-тен жүктелді. Жаңа AI сұранысы қолданылмады.",
            "generated_saved" => "Жоспар AI арқылы құрылып, cache-ке сақталды.",
            "no_tasks" => "Орындалудағы тапсырмалар жоқ. Алдымен тапсырма қосыңыз.",
            "priority" => "Маңыздылық",
            "type" => "Түрі",
            "deadline" => "Мерзім",
            "time" => "Уақыт",
            "why" => "Себебі",
            "refresh" => "Қайта құру",
            "manual_task" => "Қолмен қосылған тапсырма",
            "ai_task" => "Материалдан құрылған AI тапсырма",
            "critical" => "Өте маңызды",
            "high" => "Жоғары",
            "medium" => "Орташа",
            "low" => "Төмен"
        ]
    ];

    return $texts[$lang][$key] ?? $texts["en"][$key] ?? $key;
}

function outputLanguageName() {
    global $lang;

    if ($lang === "ru") {
        return "Russian";
    }

    if ($lang === "kz") {
        return "Kazakh";
    }

    return "English";
}

function displayPriority($priority) {
    $p = strtolower(trim($priority));

    if (strpos($p, "critical") !== false || strpos($p, "крит") !== false || strpos($p, "өте") !== false) {
        return rpText("critical");
    }

    if (strpos($p, "high") !== false || strpos($p, "выс") !== false || strpos($p, "жоғ") !== false) {
        return rpText("high");
    }

    if (strpos($p, "medium") !== false || strpos($p, "сред") !== false || strpos($p, "орта") !== false) {
        return rpText("medium");
    }

    if (strpos($p, "low") !== false || strpos($p, "низ") !== false || strpos($p, "төмен") !== false) {
        return rpText("low");
    }

    return $priority;
}

/* =========================
   GET USER TASKS
========================= */
$stmt = $conn->prepare("
    SELECT 
        id,
        title,
        description,
        notes,
        deadline,
        due_date,
        material_id,
        status,
        created_at
    FROM tasks
    WHERE user_id = ?
    AND status = 'pending'
    ORDER BY
        CASE
            WHEN COALESCE(NULLIF(deadline, '0000-00-00'), NULLIF(due_date, '0000-00-00')) IS NULL THEN 4
            WHEN COALESCE(NULLIF(deadline, '0000-00-00'), NULLIF(due_date, '0000-00-00')) < CURDATE() THEN 1
            WHEN COALESCE(NULLIF(deadline, '0000-00-00'), NULLIF(due_date, '0000-00-00')) = CURDATE() THEN 2
            WHEN COALESCE(NULLIF(deadline, '0000-00-00'), NULLIF(due_date, '0000-00-00')) <= DATE_ADD(CURDATE(), INTERVAL 3 DAY) THEN 3
            ELSE 4
        END,
        COALESCE(NULLIF(deadline, '0000-00-00'), NULLIF(due_date, '0000-00-00')) ASC,
        created_at ASC
");

if (!$stmt) {
    die("Prepare failed: " . $conn->error);
}

$stmt->bind_param("i", $user_id);
$stmt->execute();

$result = $stmt->get_result();

while ($row = $result->fetch_assoc()) {
    $tasks[] = $row;
}

/* =========================
   HELPERS
========================= */
function detectTaskType($task) {
    $materialId = $task["material_id"] ?? null;
    $description = strtolower($task["description"] ?? "");
    $notes = strtolower($task["notes"] ?? "");

    if (
        !empty($materialId) ||
        strpos($description, "ai-generated") !== false ||
        strpos($notes, "generated from study material") !== false
    ) {
        return "AI-generated material task";
    }

    return "Manual task";
}

function suggestedTimeRange($taskType, $title) {
    $titleLower = strtolower($title);

    if ($taskType === "AI-generated material task") {
        if (
            strpos($titleLower, "solve") !== false ||
            strpos($titleLower, "calculate") !== false ||
            strpos($titleLower, "analyze") !== false ||
            strpos($titleLower, "compare") !== false ||
            strpos($titleLower, "apply") !== false ||
            strpos($titleLower, "explain") !== false ||
            strpos($titleLower, "evaluate") !== false ||
            strpos($titleLower, "describe") !== false
        ) {
            return "10-15 minutes";
        }

        return "5-10 minutes";
    }

    return "1-2 hours";
}

function deadlineValue($task) {
    $deadline = $task["deadline"] ?? "";

    if ($deadline === "" || $deadline === "0000-00-00" || $deadline === null) {
        $deadline = $task["due_date"] ?? "";
    }

    if ($deadline === "" || $deadline === "0000-00-00" || $deadline === null) {
        return "No deadline";
    }

    return $deadline;
}

/* =========================
   GENERATE PLAN
========================= */
if (isset($_POST["generate"])) {

    $task_text = "";

    foreach ($tasks as $t) {
        $title = trim($t["title"] ?? "");

        if ($title === "") {
            continue;
        }

        $taskType = detectTaskType($t);
        $deadline = deadlineValue($t);
        $timeRange = suggestedTimeRange($taskType, $title);

        $task_text .= "- Task ID: {$t['id']}\n";
        $task_text .= "  Title: {$title}\n";
        $task_text .= "  Type: {$taskType}\n";
        $task_text .= "  Deadline: {$deadline}\n";
        $task_text .= "  Suggested time range: {$timeRange}\n";
        $task_text .= "  Notes: " . trim($t["notes"] ?? "") . "\n\n";
    }

    if (trim($task_text) === "") {
        $ai_response = rpText("no_tasks");
    } else {

        $taskHash = hash("sha256", $task_text);

        /*
           v3_multilang_pretty:
           - prevents old English cached plan from appearing
           - creates separate cache for RU/KZ/EN
        */
        $cacheKey = "recovery_plan_v3_multilang_pretty_user_" . $user_id . "_" . $taskHash . "_" . $lang;

        if (!$forceRefresh) {
            $cachedPlanJson = getAiCache($conn, $cacheKey);

            if ($cachedPlanJson !== null && trim($cachedPlanJson) !== "") {
                $cachedDecoded = json_decode($cachedPlanJson, true);

                if (
                    json_last_error() === JSON_ERROR_NONE &&
                    isset($cachedDecoded["plan"]) &&
                    is_array($cachedDecoded["plan"])
                ) {
                    $plan = $cachedDecoded["plan"];
                    $usedCache = true;
                }
            }
        }

        if (empty($plan)) {

            $outputLanguage = outputLanguageName();

            $prompt = "
You are an academic recovery planner.

The student has these pending tasks:

$task_text

Create a realistic study recovery plan for the next 3 days.

OUTPUT LANGUAGE:
- Write all values in JSON in $outputLanguage.
- Translate priority, day, type, time, and reason into $outputLanguage.
- Keep dates in YYYY-MM-DD format.

IMPORTANT TIME RULES:
- Manual tasks must usually take 1-2 hours.
- AI-generated material tasks must be short review/practice tasks.
- AI-generated material tasks should usually take 5-15 minutes.
- Do NOT assign 1 hour to a small AI-generated task.
- If an AI-generated task is simple, give 5-10 minutes.
- If an AI-generated task requires solving, calculation, analysis, comparison, evaluation, or explanation, give 10-15 minutes.
- Do not overload one day.
- Prioritize by deadline first, then importance.
- Urgent deadlines must appear earlier.
- If two tasks have the same deadline, place larger manual tasks first and quick AI-generated tasks as short review blocks.

PRIORITY RULES:
- Critical: overdue, due today, or due tomorrow.
- High: due in 2-3 days.
- Medium: due later.
- Low: no clear deadline or small optional review task.

Return ONLY valid JSON.
No markdown.
No explanation outside JSON.

Format exactly like this:

{
  \"plan\": [
    {
      \"priority\": \"High\",
      \"day\": \"Day 1\",
      \"task\": \"Task name here\",
      \"type\": \"Manual task\",
      \"deadline\": \"2026-06-10\",
      \"time\": \"1.5 hours\",
      \"reason\": \"Closest deadline and larger task\"
    },
    {
      \"priority\": \"Medium\",
      \"day\": \"Day 1\",
      \"task\": \"Task name here\",
      \"type\": \"AI-generated material task\",
      \"deadline\": \"2026-06-10\",
      \"time\": \"10 minutes\",
      \"reason\": \"Quick review task from uploaded material\"
    }
  ]
}
";

            $apiKey = $_ENV["OPENAI_API_KEY"] ?? null;

            if (!$apiKey) {
                $ai_response = "Error: API key not found in .env";
            } else {
                $ch = curl_init();

                curl_setopt_array($ch, [
                    CURLOPT_URL => "https://api.openai.com/v1/chat/completions",
                    CURLOPT_RETURNTRANSFER => true,
                    CURLOPT_POST => true,
                    CURLOPT_HTTPHEADER => [
                        "Content-Type: application/json",
                        "Authorization: Bearer " . $apiKey
                    ],
                    CURLOPT_POSTFIELDS => json_encode([
                        "model" => "gpt-4o-mini",
                        "temperature" => 0.15,
                        "messages" => [
                            [
                                "role" => "user",
                                "content" => $prompt
                            ]
                        ]
                    ]),
                    CURLOPT_TIMEOUT => 60
                ]);

                $apiResult = curl_exec($ch);
                $httpCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);

                if (curl_errno($ch)) {
                    $ai_response = "cURL Error: " . curl_error($ch);
                } else {
                    $response = json_decode($apiResult, true);

                    if ($httpCode < 200 || $httpCode >= 300) {
                        $errorMessage = $response["error"]["message"] ?? $apiResult;
                        $ai_response = "OpenAI API Error: " . $errorMessage;
                    } else {
                        $raw = $response["choices"][0]["message"]["content"] ?? "";
                        $decoded = json_decode($raw, true);

                        if (
                            json_last_error() === JSON_ERROR_NONE &&
                            isset($decoded["plan"]) &&
                            is_array($decoded["plan"])
                        ) {
                            $plan = $decoded["plan"];

                            $cacheJson = json_encode(
                                ["plan" => $plan],
                                JSON_UNESCAPED_UNICODE
                            );

                            saveAiCache(
                                $conn,
                                $cacheKey,
                                "recovery_plan",
                                $user_id,
                                $cacheJson
                            );

                        } else {
                            $ai_response = "Invalid JSON returned from AI:\n" . $raw;
                        }
                    }
                }

                curl_close($ch);
            }
        }

        if (!empty($plan)) {
            $plan_json = json_encode($plan, JSON_UNESCAPED_UNICODE);

            $stmt = $conn->prepare("
                INSERT INTO recovery_plans (user_id, plan)
                VALUES (?, ?)
            ");

            if ($stmt) {
                $stmt->bind_param("is", $user_id, $plan_json);
                $stmt->execute();
            }
        }
    }
}
?>

<style>
    .recovery-status {
        margin: 18px 0;
        padding: 12px 16px;
        border-radius: 14px;
        background: #eefcf3;
        color: #137333;
        font-weight: 600;
        max-width: 760px;
    }

    .recovery-top-actions {
        display: flex;
        align-items: center;
        gap: 14px;
        flex-wrap: wrap;
    }

    .recovery-refresh-link {
        font-size: 14px;
        color: #6d5dfc;
        text-decoration: none;
        font-weight: 600;
    }

    .plan-cards {
        display: grid;
        grid-template-columns: repeat(auto-fit, minmax(285px, 1fr));
        gap: 20px;
        margin-top: 24px;
    }

    .recovery-card {
        background: rgba(255, 255, 255, 0.92);
        border-radius: 22px;
        padding: 20px;
        box-shadow: 0 18px 45px rgba(41, 49, 92, 0.10);
        border: 1px solid rgba(120, 116, 255, 0.13);
        position: relative;
        overflow: hidden;
        min-height: 250px;
    }

    .recovery-card::before {
        content: "";
        position: absolute;
        top: 0;
        left: 0;
        height: 6px;
        width: 100%;
        background: linear-gradient(90deg, #6d5dfc, #9b5cff);
    }

    .recovery-card-header {
        display: flex;
        justify-content: space-between;
        align-items: flex-start;
        gap: 12px;
        margin-bottom: 14px;
    }

    .recovery-day {
        font-size: 18px;
        font-weight: 800;
        color: #111827;
    }

    .priority-badge {
        padding: 6px 10px;
        border-radius: 999px;
        font-size: 12px;
        font-weight: 800;
        background: #f4f0ff;
        color: #6d28d9;
        white-space: nowrap;
    }

    .recovery-task-title {
        font-size: 17px;
        font-weight: 800;
        line-height: 1.35;
        color: #111827;
        margin-bottom: 14px;
    }

    .recovery-info {
        display: grid;
        gap: 9px;
        font-size: 14px;
        color: #374151;
        line-height: 1.45;
    }

    .recovery-row {
        display: grid;
        grid-template-columns: 88px 1fr;
        gap: 10px;
    }

    .recovery-label {
        font-weight: 800;
        color: #6b7280;
    }

    .recovery-value {
        color: #1f2937;
    }

    .time-pill {
        display: inline-block;
        padding: 5px 10px;
        border-radius: 999px;
        background: #fff7ed;
        color: #c2410c;
        font-weight: 800;
    }
</style>

<div class="page-shell">

    <div class="page-hero">
        <h2><?= t("ai_recovery_plan") ?></h2>
    </div>

    <section class="detail-card">
        <div class="recovery-top-actions">
            <form method="POST">
                <button type="submit" name="generate">
                    <?= t("generate_recovery_plan") ?>
                </button>
            </form>

            <a
                class="recovery-refresh-link"
                href="recovery-plan.php?refresh_ai=1"
            >
                <?= rpText("refresh") ?>
            </a>
        </div>

        <?php if (!empty($plan)): ?>
            <div class="recovery-status">
                <?= $usedCache ? rpText("cache_loaded") : rpText("generated_saved") ?>
            </div>
        <?php endif; ?>

        <?php if (!empty($ai_response)): ?>
            <pre><?= htmlspecialchars($ai_response) ?></pre>
        <?php endif; ?>
    </section>

    <h3><?= t("latest_ai_plan") ?></h3>

    <div class="plan-cards">

        <?php if (!empty($plan)): ?>

            <?php foreach ($plan as $item): ?>

                <?php
                    $priority = displayPriority($item["priority"] ?? "");
                    $day = $item["day"] ?? "";
                    $task = $item["task"] ?? "";
                    $type = $item["type"] ?? "";
                    $deadline = $item["deadline"] ?? "";
                    $time = $item["time"] ?? "";
                    $reason = $item["reason"] ?? "";
                ?>

                <div class="recovery-card">

                    <div class="recovery-card-header">
                        <div class="recovery-day">
                            <?= htmlspecialchars($day) ?>
                        </div>

                        <div class="priority-badge">
                            <?= htmlspecialchars($priority) ?>
                        </div>
                    </div>

                    <div class="recovery-task-title">
                        <?= htmlspecialchars($task) ?>
                    </div>

                    <div class="recovery-info">

                        <div class="recovery-row">
                            <div class="recovery-label"><?= rpText("type") ?></div>
                            <div class="recovery-value"><?= htmlspecialchars($type) ?></div>
                        </div>

                        <div class="recovery-row">
                            <div class="recovery-label"><?= rpText("deadline") ?></div>
                            <div class="recovery-value"><?= htmlspecialchars($deadline) ?></div>
                        </div>

                        <div class="recovery-row">
                            <div class="recovery-label"><?= rpText("time") ?></div>
                            <div class="recovery-value">
                                <span class="time-pill">⏱ <?= htmlspecialchars($time) ?></span>
                            </div>
                        </div>

                        <div class="recovery-row">
                            <div class="recovery-label"><?= rpText("why") ?></div>
                            <div class="recovery-value"><?= htmlspecialchars($reason) ?></div>
                        </div>

                    </div>

                </div>

            <?php endforeach; ?>

        <?php endif; ?>

    </div>

</div>

<?php include("includes/footer.php"); ?>